language: ruby
services:
    - docker

env:
    - VERSION=$(git describe --tags)

before_install:
    - echo "Construyendo version $VERSION"
    - docker build -t srlobo/challenge:$VERSION .
    - docker image ls

jobs:
 include:
  - stage: test
    install: true
    script: docker run --rm -it srlobo/challenge:$VERSION rspec specs/
  - stage: upload
    install: true
    script: docker push srlobo/challenge:$VERSION
